name: cnyiot-proxy
version: v1.0.1
slug: cnyiot-proxy
codenotary: peakliuz@outlook.com
description: '以REST Api方式提供晨域智能电表的用电信息'
url: https://github.com/peakliuz/cnyiot-proxy
image: peakliuz/cnyiot-proxy
init: false
arch:
  - amd64
ports:
  6232/tcp: 6232
options:
  username: null
  password: 123456
  key: null
schema:
  username: str
  password: str
  key: str
